### ISSUE TITLE
Caption Enhancement

### ISSUE THREAD

**Issue by dravenst** [thumbsup/node-thumbsup#24]
I create photo captions currently in Google Picasa.  These captions are saved in the IPTC block of the image.  I found some code to allow you to retrieve these using the ImageMagick identify function.  

It would be great to add these to the exif data you're retrieving in exif.js currently.

``` js
var im  = require('imagemagick');
...
function(callback){
    im.identify(['-format', '%[IPTC:2:120]', filePath ], function(err, metadata){
        if (err) return callback(new Error('Failed to read caption ' + err + filePath));
    callback(null, { 
        caption: metadata ? metadata.trimRight() : ''
});
```

**Comment by brentrobbins** [comment]
@dravenst is there any chance you would roll this feature into thumbsup?

**Comment by rprieto** [comment]
Sorry, dropped the ball on that one! Did I miss the link to the example file?

It should be relatively straight forward to integrate, with the code that @dravenst wrote (although `thumbsup` uses `graphicsmagick`, but I imagine it has similar capabilities).

**Comment by brentrobbins** [comment]
Unfortunately I am not nodejs programer or I would try, but I can send you these test images with caption data to test.

![nature-q-c-800-600-3](https://cloud.githubusercontent.com/assets/727491/8122289/fdab01c6-1074-11e5-8334-4df09ce80884.jpg)
![nature-q-c-800-600-4](https://cloud.githubusercontent.com/assets/727491/8122290/fdade3aa-1074-11e5-8028-656eb36926c0.jpg)
![nature-q-c-800-600-5](https://cloud.githubusercontent.com/assets/727491/8122291/fdae2e82-1074-11e5-91c5-5b51f1b8252a.jpg)

**Comment by dravenst** [comment]
I did create a fork with some new options including the feature to read captions from the image files.

**Comment by rprieto** [comment]
Sorry I was unavailable for the last 2 months. That's awesome @dravenst, is it something we can easily merge back in?

**Comment by rprieto** [comment]
@dravenst I just added caption support on master. You can have a look over here: http://rprieto.github.io/thumbsup/captions.html

There's been a few other changes including the move to [lightgallery](http://sachinchoolur.github.io/lightGallery), if you want to check it out.

**Comment by rprieto** [comment]
Broader question: should we always display captions, or should it be an option?

Also adding an idea from #14: we could default the caption to the file name if no EXIF/IPTC caption is found. Or should that be optional too? (i.e. we actually want it to stay blank sometimes).

Suggesting

```bash
--show-captions [true|false]
--default-captions [true|false]
```

**Comment by brentrobbins** [comment]
@rprieto I think it might be nice to have it as an option, but one enhancement I would recommend would be using the captions for the image alt tags.

**Comment by rprieto** [comment]
Good idea, thanks! So here's the current TODO list:

- [x] add support for EXIF captions
- [x] update `metadata.json` with the captions so they're only parsed once (not on every build)
- [x] display captions under the photo in full screen mode
- [ ] add support for IPTC captions (which Picasa uses)
- [ ] add command line arg to show captions or not 
- [ ] add command line arg to default captions to the filename if nothing else available
- [ ] use the caption for the image `alt` tag

**Comment by rprieto** [comment]
Fixed in [3a01c67](https://github.com/thumbsup/node-thumbsup/commit/3a01c678eb099a94b4d99f950662abe07ccdd4b7).

IPTC captions are always shows if present, which is the same behaviour as EXIF captions. Some new themes could do it differently later, e.g. showing the caption underneath every thumbnail.

**Comment by dkebler** [comment]
is this not been pushed to npm?  I just installed thumbsup from npm and there is no caption options on the CLI nor captions showing.

**Comment by rprieto** [comment]
That's odd, it should be picking up both EXIF and IPTC captions (`ImageDescription` and `Caption-Abstract` respectively). I'll have a look to see if something broke here. Thanks for raising the issue!

**Comment by rprieto** [comment]
PS: in the end for now, I didn't add a CLI argument. It always shows the caption if present, but only in the "viewer" mode (when scrolling through large photos). Is that where you're looking, or did you expect them under the thumbnails?

**Comment by dkebler** [comment]
Yes I double checked my test image has also  an IPTC tag Caption-Abstract set as well.  So according to what you wrote I should be seeing both?  or do if find the exif it ignore iptc?

As to styling.  I figured out the lg class,  but you have viewer.css loaded before ligthgallery.css.  I suggest you move it and styles.css to after lightgallery.css so one can customize.  Until I did that .lg-sub-html class changes in viewer.css were ignored.  If your intention was not to have users change that file I'd add another custom.css to the end of the imports.

**Comment by dkebler** [comment]
Ok, yes, IPTC Caption-Abstract is working.  As you say.  I deleted my exif tag and then it displayed the iptc one.  So all is good.  

BTW  Have you seen fgallery?  It uses xmp data and displays a title and description nicely formatted... There are better photo tagger programs out there for xmp then for exif/IPTC.  I suppose it wouldn't be too hard to allow custom captions where user specifies which custom xmp tags they want to use with defaults of "title" and "caption"  like fgallery uses.

**Comment by rprieto** [comment]
I didn't know about `fgallery`, I will check it out thanks! Seems similar in concept so it will be good to see what options it has and get ideas for improvements :)

Regarding the caption, you're right that `Title` is a valid IPTC field. I'd say we should read that field as well, and display whichever one of the 3 exists. Do you want to submit a PR in `input/file.js`?

More options to load captions from a text file could be useful too, maybe as a separate feature. We'd nes to think about the file format, and if it should support setting over fields.

**Comment by rprieto** [comment]
@dkebler the last update on `master` reads the caption from all standard EXIF/IPTC/XMP tags. For now it only has a single "caption", which could be split at some point into title/description as you suggested - maybe after revisiting what the UI should look like.
