### ISSUE TITLE
ffmpeg aac plugin require "experimental" flag when built from source (e.g. Ubuntu 14.04)

### ISSUE THREAD

**Issue by mholtby** [thumbsup/node-thumbsup#27]
Hi there,

It's all working beautifully on Ubuntu 14.04 for pictures but having battles with ffmpeg. Not only was it an absolute horror to get installed from src (https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) but now I am getting an error when running thumbsup.

I have a small mp4 video in my input directory and I'm getting the following error when running thumbsup at the bottom there about aac. Where do I need to add -strict -2 to get it to work?

```
root@ip-172-31-26-7:~# thumbsup --config config.json
List all files      [====================] 66/66 files
Update metadata     [====================] up to date
Original photos     [====================] 65/65 files
Photos (large)      [====================] 65/65 files
Photos (thumbs)     [====================] 65/65 files
Videos (resized)    [====================] 1/1 files

{ [Error: Command failed: ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: 
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
Trailing options were found on the commandline.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/root/mholtby-photos/Video_Testing_With_A_Longer_Album_Title_For_Pops/IMG_2595.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2015-07-20 17:44:12
  Duration: 00:00:13.93, start: 0.000000, bitrate: 2942 kb/s
    Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 960x720, 2869 kb/s, 30.01 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2015-07-20 17:44:12
      handler_name    : Core Media Video
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2015-07-20 17:44:12
      handler_name    : Core Media Audio
[aac @ 0x20aba40] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
] killed: false, code: 1, signal: null }
```

**Comment by rprieto** [comment]
Hi, thanks for the detailed report.

Do you mind making a local change to the source code, where `thumbsup` is installed?

```bash
ls `which thumbsup`
# symlink to /usr/local/lib/node_modules/thumbsup/bin/thumbsup.js
vim /usr/local/lib/node_modules/thumbsup/src/thumbs.js
# line 33
```

See [source code](https://github.com/rprieto/thumbsup/blob/master/src/output-media/thumbs.js#L33), you should be able to add `-strict -2`. If it works, i'll check on OSX as well and we should probably add it as a default.

Cheers

**Comment by mholtby** [comment]
Hi there - thanks for the quick reply.

I actually managed to get around this by upgrading Ubuntu from 14.04 to 14.10. The package ffmpeg comes back in 14.10 (with all associated dependencies) and it started working once I had installed it through apt-get.

If I get time, I will try and test your advice on 14.04 for you but you may want to just call out in the README.md that Ubuntu 14.04 has some issues with ffmpeg due to it being pulled from the default  repos.

**Comment by rprieto** [comment]
Happy to hear it's now working!

I'll mention it in the README now, and we can definitely add `-strict experimental` for the case where people build from source. Let me know how it goes.

**Comment by rprieto** [comment]
Hi @mholtby. Could you confirm if `-strict -2` worked, in which case we could add it as a default? Thanks

**Comment by rprieto** [comment]
Closing this issue for now, we can re-investigate if it's still causing issues.
