### ISSUE TITLE
Error on video poster generation

### ISSUE THREAD

**Issue by jliu70** [thumbsup/node-thumbsup#29]
Have been using Thumbsup for some time.  It's great. Recently I've received this error:

```
List all files      [====================] 8238/8238 files
Update metadata     [====================] up to date
Original photos     [====================] up to date
Original videos     [====================] up to date
Photos (large)      [====================] up to date
Photos (thumbs)     [====================] up to date
Videos (resized)    [====================] up to date
Videos (poster)     [--------------------] 1/114 files
{ [Error: Command failed: gm convert: Request did not return an image.
] code: 1, signal: null }
```

It seems to be error-ing on a video file, but I'm not sure which video file is causing the issue.  Any ideas?

Thanks!

**Comment by rprieto** [comment]
Hi, sorry to hear that! You're right there's no easy way to figure out which file has the issue right now (I've been there too :smile:). I'll make a change to get better error reporting, e.g. printing the file name. In the meantime, are you OK making a change in the local source code? I can point you in the right direction.

Then we can have a look at what's special about that particular file. Cheers

**Comment by jliu70** [comment]
Yes, I'm OK with making a change in the local source code.  If it is possible, would you please let me know what I need to change?   Thanks!

**Comment by rprieto** [comment]
Could you try the following change in [src/utils/make.js](src/utils/make.js), on line 30?

```js
options.func(task, function(err) {
  bar.tick();
  if (err) console.error('Error processing ' + task.src);
  next(err);
});
```

It won't give us full verbose debugging, but the name of the file should be a good start.

**Comment by jliu70** [comment]
Yep, that output the name of the offending file.  Thanks!

**Comment by rprieto** [comment]
That's great, I'll make the change to the next version of thumbsup, shounds like a useful debugging thing to have.

Do you know what could be wrong with the video? `thumbsup` extracts the thumbnail from the frame at `0.1sec` , so a 2 second video shouldn't be a problem. Is it worth investigating or are you just happy to just ignore this one?

**Comment by jliu70** [comment]
I'm okay with ignoring the file for my personal purposes.

If you think it's worthwhile to help with thumbsup, I'm willing to help debug the issue further if you'd like.

**Comment by rprieto** [comment]
I'm keen to understand what the issue is.

Can you check the output folder, and see what was generated? It should have generated a large video preview (1000px) extracted from the video, and a square video thumbnail (100px) cropped from the preview. I'd be interesting to see which one it failed one, or if created any invalid image files.

**Comment by jliu70** [comment]
thumbsup --input "/Volumes/FreeAgent15/Pictures/import/upload/2015" --output "/Volumes/FreeAgent15/2015" --title "2015 Gallery" --original-photos --original-videos
jeffrey-lius-imac:test jliu$ thumbsup --input "/Users/jliu/test" --output "/Users/jliu/output" --title "test" --original-videos
List all files      [====================] 1/1 files
Update metadata     [====================] 1/1 files
Original videos     [====================] 1/1 files
Photos (large)      [====================] up to date
Photos (thumbs)     [====================] up to date
Videos (resized)    [====================] 1/1 files
Videos (poster)     [--------------------] 0/1 filesError processing /Users/jliu/test/20150726_172856_iPhone_6_Plus-IMG_1938.MOV
Videos (poster)     [====================] 1/1 files

{ [Error: Command failed: gm convert: Request did not return an image.
] code: 1, signal: null }


jeffrey-lius-imac:output jliu$ ls -lR
total 8
drwxr-xr-x  4 jliu  staff  136 Sep  3 21:56 media
-rw-r--r--  1 jliu  staff  186 Sep  3 21:56 metadata.json

./media:
total 0
drwxr-xr-x  3 jliu  staff  102 Sep  3 21:56 large
drwxr-xr-x  3 jliu  staff  102 Sep  3 21:56 original

./media/large:
total 1384
-rw-r--r--  1 jliu  staff  706959 Sep  3 21:56 20150726_172856_iPhone_6_Plus-IMG_1938.mp4

./media/original:
total 3080
-rw-------  1 jliu  staff  1574058 Sep  3 21:56 20150726_172856_iPhone_6_Plus-IMG_1938.MOV
jeffrey-lius-imac:output jliu$

**Comment by rprieto** [comment]
Hi @jliu70, sorry to revive this really old issue.
If this happens to anyone else, you can now easily get a full debug log using:

```bash
DEBUG="*" thumbsup [options]
```

This should help identify files that are causing trouble.
